CREATE TABLE PEN_SERVICES_SAGA
(
    SAGA_ID     RAW(16)              NOT NULL,
    STUDENT_ID  RAW(16),
    SAGA_NAME   VARCHAR2(50)         NOT NULL,
    SAGA_STATE  VARCHAR2(100)        NOT NULL,
    PAYLOAD     BLOB                 NOT NULL,
    STATUS      VARCHAR2(20)         NOT NULL,
    CREATE_USER VARCHAR2(32)         NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_USER VARCHAR2(32)         NOT NULL,
    UPDATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PEN_REQUEST_BATCH_SAGA_PK PRIMARY KEY (SAGA_ID)
);
CREATE INDEX PEN_SERVICES_SAGA_STATUS_IDX ON PEN_SERVICES_SAGA (STATUS);
CREATE INDEX PEN_SERVICES_SAGA_STUDENT_ID_IDX ON PEN_SERVICES_SAGA (STUDENT_ID);

CREATE TABLE PEN_SERVICES_SAGA_EVENT_STATES
(
    SAGA_EVENT_ID       RAW(16)              NOT NULL,
    SAGA_ID             RAW(16)              NOT NULL,
    SAGA_EVENT_STATE    VARCHAR2(100)        NOT NULL,
    SAGA_EVENT_OUTCOME  VARCHAR2(100)        NOT NULL,
    SAGA_STEP_NUMBER    NUMBER(4)            NOT NULL,
    SAGA_EVENT_RESPONSE BLOB                 NOT NULL,
    CREATE_USER         VARCHAR2(32)         NOT NULL,
    CREATE_DATE         DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_USER         VARCHAR2(32)         NOT NULL,
    UPDATE_DATE         DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT STUDENT_PROFILE_SAGA_EVENT_STATES_PK PRIMARY KEY (SAGA_EVENT_ID)
);
ALTER TABLE PEN_SERVICES_SAGA_EVENT_STATES
    ADD CONSTRAINT PEN_SERVICES_SAGA_EVENT_STATES_SAGA_ID_FK FOREIGN KEY (SAGA_ID) REFERENCES PEN_SERVICES_SAGA (SAGA_ID);
