CREATE TABLE PEN_NAME_TEXT
(
    RECORD_NUMBER       NUMBER               NOT NULL,
    INVALID_TEXT        VARCHAR2(100)        NOT NULL,
    LEGAL_SURNAME_CHECK VARCHAR2(2),
    LEGAL_GIVEN_CHECK   VARCHAR2(2),
    LEGAL_MIDDLE_CHECK  VARCHAR2(2),
    USUAL_SURNAME_CHECK VARCHAR2(2),
    USUAL_GIVEN_CHECK   VARCHAR2(2),
    USUAL_MIDDLE_CHECK  VARCHAR2(2),
    EFFECTIVE_DATE      DATE                 NOT NULL,
    EXPIRY_DATE         DATE                 NOT NULL,
    CREATE_USER         VARCHAR2(32)         NOT NULL,
    CREATE_DATE         DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_USER         VARCHAR2(32)         NOT NULL,
    UPDATE_DATE         DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PEN_NAME_TEXT_PK PRIMARY KEY (RECORD_NUMBER)
);
INSERT INTO PEN_NAME_TEXT
SELECT
    TRIM(RECORD_NUMBER),
    TRIM(INVALID_TEXT),
    TRIM(LEGAL_SURNAME_CHECK),
    TRIM(LEGAL_GIVEN_CHECK),
    TRIM(LEGAL_MIDDLE_CHECK),
    TRIM(USUAL_SURNAME_CHECK),
    TRIM(USUAL_GIVEN_CHECK),
    TRIM(USUAL_MIDDLE_CHECK),
    TRIM(TO_DATE(EFFECTIVE_DATE, 'YYYYMMDD')),
    TRIM(TO_DATE(EXPIRY_DATE, 'YYYYMMDD')),
    TRIM(CREATE_USER_NAME),
    TRIM(CREATE_DATE),
    TRIM(UPDATE_USER_NAME),
    TRIM(UPDATE_DATE)
FROM PEN_NAME_TEXT@PENLINK.WORLD;
